---
# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml

collections:
  # Community general collection
  - name: community.general
    version: ">=8.0.0"

  # POSIX collection
  - name: ansible.posix
    version: ">=1.5.0"

roles: []
  # Add external roles here if needed
  # - name: geerlingguy.docker
  #   version: "7.0.0"
